runtime: nodejs18
instance_class: F1
service: server-students

# Configure readiness check
readiness_check:
  path: "/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

# Configure environment variables
env_variables:
  PORT: 3001

# Map all routes to the app
handlers:
  - url: /.*
    script: auto
